<!-- Do not use XML namespaces here (<Project xmlns="...">), because it would break patching of version numbers during builds on AppVeyor (https://github.com/appveyor/website/pull/409) -->
<Project>
  <PropertyGroup>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="GitExtensions.Extensibility" Version="1.0.0.118" />
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
		<PackageVersion Include="System.ComponentModel.Composition" Version="6.0.0" />
	</ItemGroup>
</Project>